openapi: 3.0.3
info:
  title: Principal Rate Limits API
  version: 1.0.0
servers:
  - url: https://example.okta.com
tags:
  $ref: ../base.yaml#/tags
paths:
  /api/v1/principal-rate-limits:
    get:
      summary: List all principal rate limits
      description: Lists all Principal Rate Limit entities considering the provided parameters
      operationId: listPrincipalRateLimitEntities
      parameters:
        - name: filter
          in: query
          description: |-
            Filters the list of principal rate limit entities by the provided principal type (`principalType`). For example,
            `filter=principalType eq "SSWS_TOKEN"` or `filter=principalType eq "OAUTH_CLIENT"`.
          schema:
            type: string
          required: true
        - name: after
          in: query
          description: The cursor to use for pagination. It's an opaque string that specifies your current location in the list and is obtained from the `Link` response header. See [Pagination](https://developer.okta.com/docs/api/#pagination).
          schema:
            type: string
        - name: limit
          in: query
          description: Specifies the number of items to return in a single response page.
          schema:
            type: integer
            format: int32
            default: 20
            maximum: 50
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSListAll:
                  $ref: '#/components/examples/PrincipalRateLimitsSSWSListAllExample'
                OAuthClientListAll:
                  $ref: '#/components/examples/PrincipalRateLimitsOAuthClientListAllExample'
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.read
      tags:
        - PrincipalRateLimit
    post:
      summary: Create a principal rate limit
      description: Creates a new principal rate limit entity. Okta only allows one principal rate limit entity per org and principal.
      operationId: createPrincipalRateLimitEntity
      x-codegen-request-body-name: entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrincipalRateLimitEntity'
            examples:
              SSWSToken:
                $ref: '#/components/examples/PrincipalRateLimitEntityRequestSSWSToken'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: '#/components/examples/PrincipalRateLimitEntityResponseSSWSToken'
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.manage
      tags:
        - PrincipalRateLimit
    x-okta-team-detail:
      x-team-slack: eng-performance
  /api/v1/principal-rate-limits/{principalRateLimitId}:
    parameters:
      - $ref: '#/components/parameters/pathPrincipalRateLimitId'
    get:
      summary: Retrieve a principal rate limit
      description: Retrieves a principal rate limit entity by `principalRateLimitId`
      operationId: getPrincipalRateLimitEntity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: '#/components/examples/PrincipalRateLimitEntityResponseSSWSToken'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.read
      tags:
        - PrincipalRateLimit
    put:
      summary: Replace a principal rate limit
      description: Replaces a principal rate limit entity by `principalRateLimitId`
      operationId: replacePrincipalRateLimitEntity
      x-codegen-request-body-name: entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrincipalRateLimitEntity'
            examples:
              SSWSToken:
                $ref: '#/components/examples/PrincipalRateLimitEntityReplaceRequestSSWSToken'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: '#/components/examples/PrincipalRateLimitEntityReplaceResponseSSWSToken'
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.manage
      tags:
        - PrincipalRateLimit
    x-okta-team-detail:
      x-team-slack: eng-performance
components:
  examples:
    PrincipalRateLimitEntityRequestSSWSToken:
      summary: Create a principal rate limit entity request example
      value:
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
    PrincipalRateLimitEntityResponseSSWSToken:
      summary: Create a principal rate limit entity response example
      value:
        id: 0oacamvryxiyMqgiY1e5
        orgId: org1234
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
        createdDate: '2022-05-19T20:05:32.720Z'
        createdBy: 00u7xut94qEWYx5ss1d4
        lastUpdate: '2022-05-20T21:13:07.410Z'
        lastUpdatedBy: 00u7xut94qEWYx5ss1d4
    PrincipalRateLimitEntityReplaceRequestSSWSToken:
      summary: Replace a principal rate limit entity request
      value:
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
    PrincipalRateLimitEntityReplaceResponseSSWSToken:
      summary: Replace a principal rate limit entity response example
      value:
        id: 0oacamvryxiyMqgiY1e5
        orgId: org1234
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
        createdDate: '2022-05-19T20:05:32.720Z'
        createdBy: 00u7xut94qEWYx5ss1d4
        lastUpdate: '2022-05-20T21:13:07.410Z'
        lastUpdatedBy: 00u7xut94qEWYx5ss1d4
    PrincipalRateLimitsSSWSListAllExample:
      summary: List all SSWS API token principal rate limits
      value:
        - id: prlh5hd7qct3aHDry1f6
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 00T14q3ns31qMEJUU1d7
          principalType: SSWS_TOKEN
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: 2024-09-12T17:28:56.000Z
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: 2024-09-12T17:28:56.000Z
          createdBy: 00u7xut94qEWYx5ss1d4
        - id: prlid6w9ilOWlVbpG1f6
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 00T16ewcxyIrMV6Lb1d7
          principalType: SSWS_TOKEN
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: 2024-11-13T17:07:14.000Z
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: 2024-11-13T17:07:14.000Z
          createdBy: 00uid52637YwIXkJq1d4
    PrincipalRateLimitsOAuthClientListAllExample:
      summary: List all OAuth 2.0 client principal rate limits
      value:
        - id: prl7yh347wuzN5P1C1e7
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 0oa7yh346zIE1y84p1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 40
          defaultConcurrencyPercentage: 40
          lastUpdate: 2024-11-29T14:56:06.000Z
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: 2023-05-02T20:37:38.000Z
          createdBy: 00uid52637YwIXkJq1d4
        - id: prlbqdob5bhM6nff61e7
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 0oabqdob4da0JGuMf1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: 2023-12-07T21:58:02.000Z
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: 2023-12-07T21:58:02.000Z
          createdBy: 00uid52637YwIXkJq1d4
        - id: prlcamvrzvkglWHqR1e7
          orgId: 00o7xut90ucsjAQ7S1d7
          principalId: 0oacamvryxiyMqgiY1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: 2024-01-12T20:59:18.000Z
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: 2024-01-12T20:59:18.000Z
          createdBy: 00uid52637YwIXkJq1d4
  parameters:
    pathPrincipalRateLimitId:
      name: principalRateLimitId
      in: path
      schema:
        type: string
        example: 0oacamvryxiyMqgiY1d7
      required: true
      description: ID of the principal rate limit
  schemas:
    PrincipalRateLimitEntity:
      title: PrincipalRateLimitEntity
      description: ''
      type: object
      properties:
        createdBy:
          description: The Okta user ID of the user who created the principle rate limit entity
          type: string
          readOnly: true
        createdDate:
          description: The date and time the principle rate limit entity was created
          type: string
          format: date-time
          readOnly: true
        defaultConcurrencyPercentage:
          description: The default percentage of a given concurrency limit threshold that the owning principal can consume
          type: integer
        defaultPercentage:
          description: The default percentage of a given rate limit threshold that the owning principal can consume
          type: integer
        id:
          description: The unique identifier of the principle rate limit entity
          type: string
          readOnly: true
        lastUpdate:
          description: The date and time the principle rate limit entity was last updated
          type: string
          format: date-time
          readOnly: true
        lastUpdatedBy:
          description: The Okta user ID of the user who last updated the principle rate limit entity
          type: string
          readOnly: true
        orgId:
          description: The unique identifier of the Okta org
          type: string
          readOnly: true
        principalId:
          description: The unique identifier of the principal. This is the ID of the API token or OAuth 2.0 app.
          type: string
        principalType:
          $ref: '#/components/schemas/PrincipalType'
      required:
        - principalId
        - principalType
    PrincipalType:
      type: string
      description: The type of principal, either an API token or an OAuth 2.0 app
      enum:
        - SSWS_TOKEN
        - OAUTH_CLIENT
  securitySchemes:
    $ref: ../base.yaml#/components/securitySchemes
