openapi: 3.0.3
info:
  title: Identity Sources API
  version: 1.0.0
servers:
  - url: https://example.okta.com
tags:
  $ref: ../base.yaml#/tags
paths:
  /api/v1/identity-sources/{identitySourceId}/sessions:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
    get:
      summary: List all identity source sessions
      description: Lists all identity source sessions for the given identity source instance
      operationId: listIdentitySourceSessions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdentitySourceSession'
              examples:
                sessionsList:
                  $ref: '#/components/examples/ListSessionsResponseForGetSessions'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.read
      tags:
        - IdentitySource
    post:
      summary: Create an identity source session
      description: Creates an identity source session for the given identity source instance
      operationId: createIdentitySourceSession
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentitySourceSession'
              examples:
                session:
                  $ref: '#/components/examples/GetSessionResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    x-okta-team-detail:
      x-team-slack: eng-iga
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    get:
      summary: Retrieve an identity source session
      description: Retrieves an identity source session for a given identity source ID and session ID
      operationId: getIdentitySourceSession
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentitySourceSession'
              examples:
                session:
                  $ref: '#/components/examples/GetSessionResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.read
      tags:
        - IdentitySource
    delete:
      summary: Delete an identity source session
      description: Deletes an identity source session for a given identity source ID and session Id
      operationId: deleteIdentitySourceSession
      responses:
        '204':
          description: No Content
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    x-okta-team-detail:
      x-team-slack: eng-iga
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-delete:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the data to be deleted in Okta
      description: Uploads external IDs of entities that need to be deleted in Okta from the identity source for the given session
      operationId: uploadIdentitySourceDataForDelete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkDeleteRequestBody'
            examples:
              bulkDeletePayload:
                $ref: '#/components/examples/bulkDeletePayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    x-okta-team-detail:
      x-team-slack: eng-iga
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-upsert:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the data to be upserted in Okta
      description: Uploads entities that need to be inserted or updated in Okta from the identity source for the given session
      operationId: uploadIdentitySourceDataForUpsert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkUpsertRequestBody'
            examples:
              bulkUpsertPayload:
                $ref: '#/components/examples/bulkUpsertPayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    x-okta-team-detail:
      x-team-slack: eng-iga
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/start-import:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Start the import from the identity source
      description: Starts the import from the identity source described by the uploaded bulk operations
      operationId: startImportFromIdentitySource
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentitySourceSession'
              examples:
                triggeredSession:
                  $ref: '#/components/examples/TriggerSessionResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    x-okta-team-detail:
      x-team-slack: eng-iga
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-groups-upsert:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the group profiles without memberships to be upserted in Okta
      description: Uploads the group profiles without memberships that need to be inserted or updated in Okta from the identity source for the given session
      operationId: uploadIdentitySourceGroupsForUpsert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGroupUpsertRequestBody'
            examples:
              bulkGroupUpsertPayload:
                $ref: '#/components/examples/bulkGroupUpsertPayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-groups-delete:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the group external IDs to be deleted in Okta
      description: Uploads external IDs of groups that need to be deleted in Okta from the identity source for the given session
      operationId: uploadIdentitySourceGroupsDataForDelete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGroupDeleteRequestBody'
            examples:
              bulkGroupDeletePayload:
                $ref: '#/components/examples/bulkGroupDeletePayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-group-memberships-upsert:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the group memberships to be upserted in Okta
      description: Uploads the group memberships that need to be inserted or updated in Okta from the identity source for the given session
      operationId: uploadIdentitySourceGroupMembershipsForUpsert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGroupMembershipsUpsertRequestBody'
            examples:
              bulkGroupMembershipsUpsertPayload:
                $ref: '#/components/examples/bulkGroupMembershipsUpsertPayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/sessions/{sessionId}/bulk-group-memberships-delete:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceSessionId'
    post:
      summary: Upload the group memberships to be deleted in Okta
      description: Uploads the group memberships that need to be deleted in Okta from the identity source for the given session
      operationId: uploadIdentitySourceGroupMembershipsForDelete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGroupMembershipsDeleteRequestBody'
            examples:
              bulkGroupMembershipsDeletePayload:
                $ref: '#/components/examples/bulkGroupMembershipsDeletePayload'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/users:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
    post:
      summary: Create an identity source user
      description: Creates a user in an identity source for the given identity source instance
      operationId: createIdentitySourceUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestSchema'
            examples:
              userCreatePayload:
                $ref: '#/components/examples/UserPayload'
      responses:
        '200':
          description: Success
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/users/{externalId}:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathExternalUserId'
    get:
      summary: Retrieve an identity source user
      description: Retrieves a user by external ID in an identity source for the given identity source instance
      operationId: getIdentitySourceUser
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseSchema'
              examples:
                userResponse:
                  $ref: '#/components/examples/UserResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.read
      tags:
        - IdentitySource
    patch:
      summary: Update an identity source user
      description: Updates a user to an identity source for the given identity source instance and external ID
      operationId: updateIdentitySourceUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersUpdateRequestSchema'
            examples:
              userCreatePayload:
                $ref: '#/components/examples/UserUpdatePayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseSchema'
              examples:
                userResponse:
                  $ref: '#/components/examples/UserUpdateResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    put:
      summary: Replace an existing identity source user
      description: Replaces an existing user for the given identity source instance and external ID
      operationId: replaceExistingIdentitySourceUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestSchema'
            examples:
              userReplacePayload:
                $ref: '#/components/examples/UserReplacePayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseSchema'
              examples:
                userResponse:
                  $ref: '#/components/examples/UserReplaceResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    delete:
      summary: Delete an identity source user
      description: Deletes a user in an identity source for the given identity source instance and external ID
      operationId: deleteIdentitySourceUser
      responses:
        '204':
          description: No Content
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/groups:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
    post:
      summary: Create an identity source group
      description: Creates a group in an identity source for the given identity source instance
      operationId: createIdentitySourceGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsRequestSchema'
            examples:
              createGroupsPayload:
                $ref: '#/components/examples/GroupsPayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsResponseSchema'
              examples:
                group:
                  $ref: '#/components/examples/GroupsResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/groups/{groupOrExternalId}:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceGroupOrExternalId'
    post:
      summary: Update an identity source group
      description: Updates a group to an identity source for the given identity source instance and group ID
      operationId: updateIdentitySourceGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsRequestSchema'
            examples:
              createGroupsPayload:
                $ref: '#/components/examples/GroupsPayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsResponseSchema'
              examples:
                group:
                  $ref: '#/components/examples/GroupsResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    delete:
      summary: Delete an identity source group
      description: Deletes a group in an identity source for a given identity source ID and group ID
      operationId: deleteIdentitySourceGroup
      responses:
        '204':
          description: No Content
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    get:
      summary: Retrieve an identity source group
      description: Retrieves a group from an identity source for a given identity source ID and group ID or external ID
      operationId: getIdentitySourceGroup
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsResponseSchema'
              examples:
                group:
                  $ref: '#/components/examples/GroupsResponse'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.read
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/groups/{groupOrExternalId}/membership:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceGroupOrExternalId'
    post:
      summary: Create the memberships for the given identity source group
      description: Creates the group memberships for the given identity source group
      operationId: createIdentitySourceGroupsMemberships
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembershipRequestSchema'
            examples:
              createGroupsPayload:
                $ref: '#/components/examples/MembershipPayload'
      responses:
        '204':
          description: No Content
        '400':
          $ref: ./Common.yaml#/components/responses/ErrorApiValidationFailed400
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
    get:
      summary: Retrieve the memberships for the given identity source group
      description: Retrieves the group memberships for the given identity source group in the given identity source instance
      operationId: getIdentitySourceGroupMemberships
      parameters:
        - $ref: ./Common.yaml#/components/parameters/queryAfter
        - name: limit
          in: query
          description: |-
            Specifies the number of group membership results in a page. Okta recommends using a specific value other than the default or maximum.
            If your request times out, retry your request with a smaller `limit` and [page the results](https://developer.okta.com/docs/api/#pagination).
          schema:
            type: integer
            format: int32
            maximum: 1000
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupMembershipsResponseSchema'
              examples:
                groupMembershipsResponse:
                  $ref: '#/components/examples/GroupMemberships'
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.read
      tags:
        - IdentitySource
  /api/v1/identity-sources/{identitySourceId}/groups/{groupOrExternalId}/membership/{memberExternalId}:
    parameters:
      - $ref: '#/components/parameters/pathIdentitySourceId'
      - $ref: '#/components/parameters/pathIdentitySourceGroupOrExternalId'
      - $ref: '#/components/parameters/pathIdentitySourceMemberExternalId'
    delete:
      summary: Delete the memberships for the specified identity source group
      description: Deletes group memberships for the specified identity source group using member external IDs
      operationId: deleteIdentitySourceGroupMemberships
      responses:
        '204':
          description: No Content
        '403':
          $ref: ./Common.yaml#/components/responses/ErrorAccessDenied403
        '404':
          $ref: ./Common.yaml#/components/responses/ErrorResourceNotFound404
        '429':
          $ref: ./Common.yaml#/components/responses/ErrorTooManyRequests429
      security:
        - apiToken: []
        - oauth2:
            - okta.identitySources.manage
      tags:
        - IdentitySource
components:
  examples:
    GetSessionResponse:
      value:
        id: aps1qqonvr2SZv6o70h8
        identitySourceId: 0oa3l6l6WK6h0R0QW0g4
        status: CREATED
        importType: INCREMENTAL
        created: 2022-04-04T15:56:05.000Z
        lastUpdated: 2022-05-05T16:15:44.000Z
    ListSessionsResponseForGetSessions:
      value:
        - id: aps1qqonvr2SZv6o70h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: CREATED
          importType: INCREMENTAL
          created: 2022-04-04T15:56:05.000Z
          lastUpdated: 2022-05-05T16:15:44.000Z
        - id: aps1quck606ngubVq0h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: TRIGGERED
          importType: INCREMENTAL
          created: 2022-04-04T16:56:05.000Z
          lastUpdated: 2022-05-05T17:15:44.000Z
        - id: aps1qzy2acb5jDlUc0h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: IN_PROGRESS
          importType: INCREMENTAL
          created: 2022-04-04T17:56:05.000Z
          lastUpdated: 2022-05-05T18:15:44.000Z
        - id: aps1qqne8c1JHkMdF0h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: EXPIRED
          importType: INCREMENTAL
          created: 2022-04-04T18:56:05.000Z
          lastUpdated: 2022-05-05T19:15:44.000Z
        - id: aps1qqonvr2SZv6o70h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: CLOSED
          importType: INCREMENTAL
          created: 2022-04-04T19:56:05.000Z
          lastUpdated: 2022-05-05T20:15:44.000Z
    TriggerSessionResponse:
      value:
        - id: aps1qqonvr2SZv6o70h8
          identitySourceId: 0oa3l6l6WK6h0R0QW0g4
          status: TRIGGERED
          importType: INCREMENTAL
          created: 2022-04-04T15:56:05.000Z
          lastUpdated: 2022-05-05T18:15:44.000Z
    bulkDeletePayload:
      value:
        entityType: USERS
        profiles:
          - externalId: EXT123456784C2IF
          - externalId: EXT123456784C3IF
          - externalId: EXT123456784C4IF
    bulkUpsertPayload:
      value:
        entityType: USERS
        profiles:
          - externalId: EXT123456784C2IF
            profile:
              userName: isaac.brock@example.com
              firstName: Isaac
              lastName: Brock
              email: isaac.brock@example.com
              secondEmail: isaac2.brock@example.com
              mobilePhone: 123-456-7890
              homeAddress: '10800 NE 8th St #600, Bellevue, WA 98004'
          - externalId: EXT123456784C3IF
            profile:
              userName: jane.smith@example.com
              firstName: Jane
              lastName: Smith
              email: jane.smith@example.com
              secondEmail: jane2.smith@example.com
              mobilePhone: 555-123-4567
              homeAddress: Seattle, WA 98101
    bulkGroupUpsertPayload:
      value:
        profiles:
          - externalId: GROUPEXT123456784C2IF
            profile:
              displayName: group1
              description: group1 description
          - externalId: GROUPEXT123456784C3IF
            profile:
              displayName: group2
              description: group2 description
    bulkGroupDeletePayload:
      value:
        externalIds:
          - GROUPEXT123456784C2IF
          - GROUPEXT123456784C3IF
          - GROUPEXT123456784C4IF
    bulkGroupMembershipsUpsertPayload:
      value:
        memberships:
          - groupExternalId: GROUPEXT123456784C2IFA
            memberExternalIds:
              - USEREXT123456784C2IFA
              - USEREXT123456784C3IFB
              - USEREXT123456784C4IFC
          - groupExternalId: GROUPEXT123456784C2IFB
            memberExternalIds:
              - USEREXT123456784C2IFA
              - USEREXT123456784C3IFB
              - USEREXT123456784C4IFC
    bulkGroupMembershipsDeletePayload:
      value:
        memberships:
          - groupExternalId: GROUPEXT123456784C2IFA
            memberExternalIds:
              - USEREXT123456784C2IFA
              - USEREXT123456784C3IFB
              - USEREXT123456784C4IFC
          - groupExternalId: GROUPEXT123456784C2IFB
            memberExternalIds:
              - USEREXT123456784C2IFA
              - USEREXT123456784C3IFB
              - USEREXT123456784C4IFC
    GroupsPayload:
      value:
        externalId: GROUPEXT123456784C2IF
        profile:
          displayName: West Coast users
          description: All users West of The Rockies
    GroupsResponse:
      value:
        id: 00gsl4xM9ys8TdnbZ0g4
        externalId: GROUPEXT123456784C2IF
        profile:
          displayName: West Coast users
          description: All users West of The Rockies
    GroupMemberships:
      value:
        memberExternalIds:
          - USEREXT123456784C2IFA
          - USEREXT123456784C3IFB
          - USEREXT123456784C4IFC
    MembershipPayload:
      value:
        memberExternalId: USEREXT123456784C2IFA
    UserPayload:
      value:
        externalId: EXT987654321Z9Y7X
        profile:
          userName: emily.jones@example.com
          firstName: Emily
          lastName: Jones
          email: emily.jones@example.com
          secondEmail: emily.secondary@example.com
          mobilePhone: 987-654-3210
          homeAddress: '10800 NE 8th St #600, Bellevue, WA 98004'
    UserResponse:
      value:
        id: 00u7m9p9ZT8k2S2EX1f7
        externalId: EXT987654321Z9Y7X
        created: 2025-07-24T12:06:05.000Z
        lastUpdated: 2025-08-05T16:15:44.000Z
        profile:
          userName: emily.jones@example.com
          firstName: Emily
          lastName: Jones
          email: emily.jones@example.com
          secondEmail: emily.secondary@example.com
          mobilePhone: 987-654-3210
          homeAddress: '10800 NE 8th St #600, Bellevue, WA 98004'
    UserUpdatePayload:
      value:
        profile:
          firstName: Emily
          lastName: Brock
          email: emily.brock@update.com
          userName: emily.brock@update.com
    UserUpdateResponse:
      value:
        profile:
          firstName: Emily
          lastName: Brock
          email: emily.brock@update.com
          userName: emily.brock@update.com
          secondEmail: emily.secondary@example.com
          mobilePhone: 987-654-3210
          homeAddress: '10800 NE 8th St #600, Bellevue, WA 98004'
    UserReplacePayload:
      value:
        profile:
          firstName: Emily
          lastName: Brock
          email: brockly@email.com
          userName: brockly@email.com
    UserReplaceResponse:
      value:
        profile:
          firstName: Emily
          lastName: Brock
          email: brockly@email.com
          userName: brockly@email.com
          secondEmail: null
          mobilePhone: null
          homeAddress: null
  parameters:
    pathIdentitySourceId:
      name: identitySourceId
      in: path
      required: true
      description: The ID of the identity source for which the session is created
      example: 0oa3l6l6WK6h0R0QW0g4
      schema:
        type: string
    pathIdentitySourceSessionId:
      name: sessionId
      in: path
      required: true
      description: The ID of the identity source session
      example: aps1qqonvr2SZv6o70h8
      schema:
        type: string
    pathIdentitySourceExternalId:
      name: externalId
      in: path
      required: true
      description: The external ID of the identity source group
      example: GROUPEXT123456784C2IF
      schema:
        type: string
    pathIdentitySourceGroupOrExternalId:
      name: groupOrExternalId
      in: path
      required: true
      description: The Okta group ID or external ID of the identity source group
      example: 00gsl4xM9ys8TdnbZ0g4 or GROUPEXT123456784C2IF
      schema:
        type: string
    pathIdentitySourceMemberExternalId:
      name: memberExternalId
      in: path
      required: true
      description: The external ID of the identity source user
      example: USEREXT123456784C2IFA
      schema:
        type: string
    pathIdentitySourceUserId:
      name: appUserId
      in: path
      required: true
      description: The ID of the user in the identity source
      example: 00u7m9p9ZT8k2S2EX1f7
      schema:
        type: string
    pathExternalUserId:
      name: externalId
      in: path
      required: true
      description: The external ID of the user
      example: 00u7m9p9ZT8k2S2EX1f7
      schema:
        type: string
  schemas:
    BulkDeleteRequestBody:
      type: object
      properties:
        entityType:
          description: The type of data to bulk delete in a session. Currently, only `USERS` is supported.
          type: string
          enum:
            - USERS
        profiles:
          type: array
          description: Array of profiles to be deleted
          items:
            $ref: '#/components/schemas/IdentitySourceUserProfileForDelete'
    BulkUpsertRequestBody:
      type: object
      properties:
        entityType:
          description: The type of data to upsert into the session. Currently, only `USERS` is supported.
          type: string
          enum:
            - USERS
        profiles:
          type: array
          description: Array of user profiles to be uploaded
          items:
            type: object
            properties:
              externalId:
                type: string
                description: The external ID of the entity that needs to be created or updated in Okta
                maxLength: 512
              profile:
                $ref: '#/components/schemas/IdentitySourceUserProfileForUpsert'
    BulkGroupUpsertRequestBody:
      type: object
      properties:
        profiles:
          type: array
          description: Array of group profiles that needs to be inserted or updated in Okta
          minItems: 1
          maxItems: 200
          items:
            type: object
            properties:
              externalId:
                type: string
                description: The external ID of the group that needs to be created or updated in Okta
                maxLength: 255
              profile:
                $ref: '#/components/schemas/IdentitySourceGroupProfileForUpsert'
    BulkGroupDeleteRequestBody:
      type: object
      properties:
        externalIds:
          type: array
          description: Array of external IDs of groups that need to be deleted in Okta
          minItems: 1
          maxItems: 200
          items:
            type: string
            maxLength: 255
    BulkGroupMembershipsUpsertRequestBody:
      type: object
      properties:
        memberships:
          $ref: '#/components/schemas/IdentitySourceGroupMembershipsUpsertProfile'
    BulkGroupMembershipsDeleteRequestBody:
      type: object
      properties:
        memberships:
          $ref: '#/components/schemas/IdentitySourceGroupMembershipsDeleteProfile'
    IdentitySourceSession:
      type: object
      properties:
        created:
          type: string
          description: The timestamp when the identity source session was created
          format: date-time
          readOnly: true
        id:
          type: string
          description: The ID of the identity source session
          readOnly: true
        identitySourceId:
          type: string
          description: The ID of the custom identity source for which the session is created
          readOnly: true
        importType:
          type: string
          description: The type of import.  All imports are `INCREMENTAL` imports.
          readOnly: true
        lastUpdated:
          type: string
          description: The timestamp when the identity source session was created
          format: date-time
          readOnly: true
        status:
          $ref: '#/components/schemas/IdentitySourceSessionStatus'
    IdentitySourceSessionStatus:
      description: The current status of the identity source session
      type: string
      enum:
        - CREATED
        - IN_PROGRESS
        - TRIGGERED
        - COMPLETED
        - CLOSED
        - EXPIRED
        - ERROR
      x-enumDescriptions:
        CREATED: This is a new identity source session that hasn't been processed. You can upload bulk data in this stage.
        IN_PROGRESS: The bulk data is being uploaded to Okta.
        TRIGGERED: Okta is processing the import data in this session. You can't load bulk data in this stage.
        COMPLETED: The bulk data was processed and imported into Okta.
        CLOSED: The identity source session was canceled and isn't available for further activity.
        EXPIRED: This identity source session had the `CREATED` status and timed-out after 24 hours of inactivity.
        ERROR: The processing of import data in the session encountered an error. You need to open a new session to upload the data again.
    IdentitySourceUserProfileForDelete:
      type: object
      properties:
        externalId:
          type: string
          description: The external ID of the entity that needs to be deleted in Okta
          maxLength: 512
    IdentitySourceUserProfileForUpsertRequired:
      x-okta-ignore-redocly-rules-for-sdk: true
      allOf:
        - $ref: '#/components/schemas/IdentitySourceUserProfileForUpsert'
        - type: object
          required:
            - email
            - userName
          description: |-
            Contains a set of external user attributes and their values that are mapped to Okta standard and custom profile properties. See the [`profile` object](https://developer.okta.com/docs/api/openapi/okta-management/management/user/getuser#user/getuser/t=response&c=200&path=profile) and Declaration of a Custom Identity Source Schema in [Using anything as a source](https://help.okta.com/okta_help.htm?type=oie&id=ext-anything-as-a-source).
            > **Note:** Profile attributes can only be of the string type.
    IdentitySourceUserProfileForUpsert:
      type: object
      x-okta-ignore-redocly-rules-for-sdk: true
      description: |-
        Contains a set of external user attributes and their values that are mapped to Okta standard and custom profile properties. See the [`profile` object](https://developer.okta.com/docs/api/openapi/okta-management/management/user/getuser#user/getuser/t=response&c=200&path=profile) and Declaration of a Custom Identity Source Schema in [Using anything as a source](https://help.okta.com/okta_help.htm?type=oie&id=ext-anything-as-a-source).
        > **Note:** Profile attributes can only be of the string type.
      properties:
        userName:
          type: string
          description: Username of the user
          maxLength: 100
        firstName:
          type: string
          description: First name of the user
          minLength: 1
          maxLength: 50
          nullable: true
        lastName:
          type: string
          description: Last name of the user
          minLength: 1
          maxLength: 50
          nullable: true
        email:
          type: string
          format: email
          description: Email address of the user
          minLength: 5
          maxLength: 100
        secondEmail:
          type: string
          description: Alternative email address of the user
          format: email
          minLength: 5
          maxLength: 100
        mobilePhone:
          type: string
          description: Mobile phone number of the user
          maxLength: 100
          nullable: true
        homeAddress:
          type: string
          description: Home address of the user
          maxLength: 4096
          nullable: true
    IdentitySourceGroupProfileForUpsert:
      type: object
      description: |-
        Contains a set of external group attributes and their values that are mapped to Okta standard properties. See the group [`profile` object](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Group/#tag/Group/operation/getGroup!c=200&path=profile&t=response) and Declaration of a Custom Identity Source Schema in [Using anything as a source](https://help.okta.com/okta_help.htm?type=oie&id=ext-anything-as-a-source).
        > **Note:** Profile attributes can only be of the string type.
      properties:
        displayName:
          type: string
          description: Name of the group
          minLength: 1
          maxLength: 255
        description:
          type: string
          description: Description of the group
          maxLength: 1024
          nullable: true
    IdentitySourceGroupMembershipsUpsertProfile:
      type: array
      description: Array of group memberships that need to be inserted or updated in Okta
      minItems: 1
      maxItems: 200
      items:
        type: object
        properties:
          groupExternalId:
            type: string
            description: The external ID of the group whose memberships need to be inserted or updated in Okta
            maxLength: 255
          memberExternalIds:
            type: array
            description: Array of external IDs of member profiles that need to be inserted in this group in Okta
            items:
              type: string
              maxLength: 255
    IdentitySourceGroupMembershipsDeleteProfile:
      type: array
      description: Array of group memberships that need to be deleted in Okta
      minItems: 1
      maxItems: 200
      items:
        type: object
        properties:
          groupExternalId:
            type: string
            description: The external ID of the group whose memberships need to be deleted in Okta
            maxLength: 255
          memberExternalIds:
            type: array
            description: Array of external IDs of member profiles that need to be inserted in this group in Okta
            items:
              type: string
              maxLength: 255
    GroupsRequestSchema:
      type: object
      properties:
        externalId:
          type: string
          description: The external ID of the identity source group to be created
          maxLength: 255
        profile:
          $ref: '#/components/schemas/IdentitySourceGroupProfileForUpsert'
    GroupsResponseSchema:
      type: object
      properties:
        id:
          type: string
          description: The Okta group ID of the identity source group
          readOnly: true
        externalId:
          type: string
          description: The external ID of the identity source group
          maxLength: 255
        profile:
          type: object
          description: The profile information of the group
          properties:
            profile:
              $ref: '#/components/schemas/IdentitySourceGroupProfileForUpsert'
    GroupMembershipsRequestSchema:
      type: object
      properties:
        memberExternalIds:
          type: array
          description: A list of app user external IDs to be inserted in this group in Okta
          items:
            type: string
            maxLength: 255
    GroupMembershipsResponseSchema:
      type: object
      properties:
        memberExternalIds:
          type: array
          description: A list of app user external IDs that are members of the group in Okta
          items:
            type: string
            maxLength: 255
    MembershipRequestSchema:
      type: object
      properties:
        memberExternalId:
          type: string
          description: The external ID of the user to be added as a member of the group in Okta
          maxLength: 255
    UserRequestSchema:
      type: object
      properties:
        externalId:
          type: string
          description: The external ID of the user in the identity source
          maxLength: 512
        profile:
          $ref: '#/components/schemas/IdentitySourceUserProfileForUpsertRequired'
    UsersUpdateRequestSchema:
      type: object
      properties:
        profile:
          $ref: '#/components/schemas/IdentitySourceUserProfileForUpsertRequired'
    UserResponseSchema:
      type: object
      properties:
        id:
          type: string
          description: The ID of the user in the identity source
          readOnly: true
        externalId:
          type: string
          description: The external ID of the user in the identity source
          readOnly: true
          maxLength: 255
        created:
          type: string
          description: The timestamp when the user was created in the identity source
          format: date-time
          readOnly: true
        lastUpdated:
          type: string
          description: The timestamp when the user was last updated in the identity source
          format: date-time
          readOnly: true
        profile:
          $ref: '#/components/schemas/IdentitySourceUserProfileForUpsert'
  securitySchemes:
    $ref: ../base.yaml#/components/securitySchemes
